### PR TITLE
Implemented -c, --config flag and fixed CLI arg reader

### LINKED ISSUE #16: Adding -c, --config options to read from TOML file
Hi, I would like to add a feature to be able to read from a config file for you application.
The idea is to supply a -c or --config option and pass it a file path to be able to read from that config path instead of looking through your command history or memorizing the commands that you use regularly. 

This will most likely require changes to the CommandLineParser.cs file. 
This will also require the addition of a TOML parsing library, I was thinking of using [Tommy](https://www.nuget.org/packages/Tommy).
I would also like to make changes to how the command line reads arguments, the current way of reading command line options is non standard and will read it from the last parameter rather than the one directly after a flag. I would like to make it so that the input file always comes last.

### PR DESCRIPTION
**Pull request by omalk98**
## What has been done

Added feature to read TOML config files into the program.
Changed the `ParseCommandLineArgs` function to loop through the arguments and assign them accordingly. The input path will always come last in this case.

## What has been changed 

- Added the `Tommy` TOML parsing library
- Added function to read and process the TOML file in the `CommandLineParser` class
- Modified `ParseCommandLineArgs` function to read arguments in a standard way

## Notes

I implemented the basics of the CLI reading and would like to leave it up to you how you would like to handle errors more gracefully currently the code will attempt to read the config file, and exit the program if it fails to do so.
A more graceful exit strategy would be to maybe allow the config file to be ignored if it fails to read it and continue on with the CLI args.
There are also possibilities of the config file having TOML syntax errors which could crash the app, the `Tommy` library provides a graceful method that attempts to parse the table as best it can before exiting, this table can also be used to run the program regardless of the error, and simply show a warning of the syntax error.

### CODE REVIEW

File: src/CommandLineParser.cs [hunk 1]
```diff
@@ -13,58 +14,131 @@ public class CommandLineParser
...
+                        options.ShowHelp = true;
+                        return options;
+                    case "-o":
+                    case "--output":
+                        if (i + 1 < args.Length)
+                        {
+                            // Low priority: If the output path is not specified through the config file, use the one specified through CLI
+                            options.OutputPath ??= args[i + 1];
+                            i++; // Skip the next argument as it is the output file path
+                        }
```
Comment (Yousef-Majidi) [inline src/CommandLineParser.cs:37]: if the output path is not specified through the config file, we should use the default `./til` directory. 

generally speaking, if the `-c` flag is used, all other flags in the cli must be ignored.

**Review by Yousef-Majidi — CHANGES_REQUESTED** [review]

**Comment by Yousef-Majidi** [comment]
Thanks for your contribution. Mostly looking good. Please just address the comment I left in the review and we should be able to merge this.

**Review by Yousef-Majidi — APPROVED** [review]
LGTM!

This closes #16
